package com.zrzhen.logicmachine.dao;

import com.zrzhen.logicmachine.domain.Function;
import org.apache.ibatis.jdbc.SQL;

public class FunctionSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function
     *
     * @mbg.generated
     */
    public String insertSelective(Function record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("`function`");
        
        if (record.getFunction_id() != null) {
            sql.VALUES("function_id", "#{function_id,jdbcType=INTEGER}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("`name`", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getPath() != null) {
            sql.VALUES("`path`", "#{path,jdbcType=VARCHAR}");
        }
        
        if (record.getParam() != null) {
            sql.VALUES("param", "#{param,jdbcType=CHAR}");
        }
        
        if (record.getCreate_time() != null) {
            sql.VALUES("create_time", "#{create_time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdate_time() != null) {
            sql.VALUES("update_time", "#{update_time,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Function record) {
        SQL sql = new SQL();
        sql.UPDATE("`function`");
        
        if (record.getName() != null) {
            sql.SET("`name` = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getPath() != null) {
            sql.SET("`path` = #{path,jdbcType=VARCHAR}");
        }
        
        if (record.getParam() != null) {
            sql.SET("param = #{param,jdbcType=CHAR}");
        }
        
        if (record.getCreate_time() != null) {
            sql.SET("create_time = #{create_time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdate_time() != null) {
            sql.SET("update_time = #{update_time,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("function_id = #{function_id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}