package com.zrzhen.logicmachine.domain;

import java.io.Serializable;
import java.util.Date;

public class Function implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.function_id
     *
     * @mbg.generated
     */
    private Integer function_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.param
     *
     * @mbg.generated
     */
    private String param;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.create_time
     *
     * @mbg.generated
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column function.update_time
     *
     * @mbg.generated
     */
    private Date update_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table function
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.function_id
     *
     * @return the value of function.function_id
     *
     * @mbg.generated
     */
    public Integer getFunction_id() {
        return function_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.function_id
     *
     * @param function_id the value for function.function_id
     *
     * @mbg.generated
     */
    public void setFunction_id(Integer function_id) {
        this.function_id = function_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.name
     *
     * @return the value of function.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.name
     *
     * @param name the value for function.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.path
     *
     * @return the value of function.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.path
     *
     * @param path the value for function.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.param
     *
     * @return the value of function.param
     *
     * @mbg.generated
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.param
     *
     * @param param the value for function.param
     *
     * @mbg.generated
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.create_time
     *
     * @return the value of function.create_time
     *
     * @mbg.generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.create_time
     *
     * @param create_time the value for function.create_time
     *
     * @mbg.generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column function.update_time
     *
     * @return the value of function.update_time
     *
     * @mbg.generated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column function.update_time
     *
     * @param update_time the value for function.update_time
     *
     * @mbg.generated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table function
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", function_id=").append(function_id);
        sb.append(", name=").append(name);
        sb.append(", path=").append(path);
        sb.append(", param=").append(param);
        sb.append(", create_time=").append(create_time);
        sb.append(", update_time=").append(update_time);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}